-- Trigger para registrar la creación de empleados en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_insert_empleado` AFTER INSERT ON `empleado`
 FOR EACH ROW BEGIN
 	DECLARE user_id INT;
    SET user_id = @current_user_id;

INSERT INTO AUDITORIA_EMPLEADO (IDEMPLEADO, IDPUESTO, IDMUNICIPIO, IDESTADOCIVIL, EMP_IDEMPLEADO, IDTIPODOC, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2, APELLIDOCASADA, SEXO, FECHANACIMIENTO, FECHAINGRESO, NUMERODOC, NIT, ISSS, NUP, SALARIO, CORREOINSTITUCIONAL, CORREOPERSONAL, ESTADO, FECHAMODIFICACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDEMPLEADO, NEW.IDPUESTO, NEW.IDMUNICIPIO, NEW.IDESTADOCIVIL, NEW.EMP_IDEMPLEADO, NEW.IDTIPODOC, NEW.NOMBRE1, NEW.NOMBRE2, NEW.APELLIDO1, NEW.APELLIDO2, NEW.APELLIDOCASADA, NEW.SEXO, NEW.FECHANACIMIENTO, NEW.FECHAINGRESO, NEW.NUMERODOC, NEW.NIT, NEW.ISSS, NEW.NUP, NEW.SALARIO, NEW.CORREOINSTITUCIONAL, NEW.CORREOPERSONAL, NEW.ESTADO, NOW(), 'Creación', user_id);
END$$
DELIMITER ;

-- Trigger para registrar la actualización de empleados en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_update_empleado` AFTER UPDATE ON `empleado`
 FOR EACH ROW BEGIN
	DECLARE user_id INT;
    SET user_id = @current_user_id;

INSERT INTO AUDITORIA_EMPLEADO (IDEMPLEADO, IDPUESTO, IDMUNICIPIO, IDESTADOCIVIL, EMP_IDEMPLEADO, IDTIPODOC, NOMBRE1, NOMBRE2, APELLIDO1, APELLIDO2, APELLIDOCASADA, SEXO, FECHANACIMIENTO, FECHAINGRESO, NUMERODOC, NIT, ISSS, NUP, SALARIO, CORREOINSTITUCIONAL, CORREOPERSONAL, ESTADO, FECHAMODIFICACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDEMPLEADO, NEW.IDPUESTO, NEW.IDMUNICIPIO, NEW.IDESTADOCIVIL, NEW.EMP_IDEMPLEADO, NEW.IDTIPODOC, NEW.NOMBRE1, NEW.NOMBRE2, NEW.APELLIDO1, NEW.APELLIDO2, NEW.APELLIDOCASADA, NEW.SEXO, NEW.FECHANACIMIENTO, NEW.FECHAINGRESO, NEW.NUMERODOC, NEW.NIT, NEW.ISSS, NEW.NUP, NEW.SALARIO, NEW.CORREOINSTITUCIONAL, NEW.CORREOPERSONAL, NEW.ESTADO, NOW(), 'Actualización', user_id);
END$$
DELIMITER;

-- Trigger para registrar la creación en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_insert_deduccionbeneficioglobal` AFTER INSERT ON `deduccionbeneficioglobal`
 FOR EACH ROW BEGIN
    DECLARE user_id INT;
    DECLARE nombre_deduccion VARCHAR(75);
    DECLARE tipo_deduccion CHAR(1);
    SET user_id = @current_user_id;

    SELECT NOMBREDEDUCBENEF, TIPO INTO nombre_deduccion, tipo_deduccion
    FROM DEDUCCIONBENEFICIO
    WHERE IDDEDUCBENEF = NEW.IDDEDUCBENEF;

    INSERT INTO AUDITORIA_DEDUCCIONBENEFICIOGLOBAL (IDDEDUCBENEF, NOMBREDEDUCBENEF, TIPO, PROPORCIONALALSUELDO, MONTOOPORCENTAJE, ESTADO, FECHADEOPERACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDDEDUCBENEF, nombre_deduccion, tipo_deduccion, NEW.PROPORCIONALALSUELDO, NEW.MONTOOPORCENTAJE, NEW.ESTADO, NOW(), 'Inserción', user_id);
END$$
DELIMITER ;

-- Trigger para registrar la actualización en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_update_deduccionbeneficioglobal` AFTER UPDATE ON `deduccionbeneficioglobal`
 FOR EACH ROW BEGIN
    DECLARE user_id INT;
    DECLARE nombre_deduccion VARCHAR(75);
    DECLARE tipo_deduccion CHAR(1);
    SET user_id = @current_user_id;

    SELECT NOMBREDEDUCBENEF, TIPO INTO nombre_deduccion, tipo_deduccion
    FROM DEDUCCIONBENEFICIO
    WHERE IDDEDUCBENEF = NEW.IDDEDUCBENEF;

    INSERT INTO AUDITORIA_DEDUCCIONBENEFICIOGLOBAL (IDDEDUCBENEF, NOMBREDEDUCBENEF, TIPO, PROPORCIONALALSUELDO, MONTOOPORCENTAJE, ESTADO, FECHADEOPERACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDDEDUCBENEF, nombre_deduccion, tipo_deduccion, NEW.PROPORCIONALALSUELDO, NEW.MONTOOPORCENTAJE, NEW.ESTADO, NOW(), 'Actualización', user_id);
END$$
DELIMITER ;

-- Trigger para registrar la creación en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_insert_deduccionbeneficioempleado` AFTER INSERT ON `deduccionbeneficio_empleado`
 FOR EACH ROW BEGIN
    DECLARE user_id INT;
    DECLARE nombre_deduccion VARCHAR(50);
    DECLARE tipo_deduccion CHAR(1);
    SET user_id = @current_user_id;

    SELECT NOMBREDEDUCBENEF, TIPO INTO nombre_deduccion, tipo_deduccion
    FROM DEDUCCIONBENEFICIO
    WHERE IDDEDUCBENEF = NEW.IDDEDUCBENEF;

    INSERT INTO AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO (IDDEDUCBENEF, NOMBREDEDUCBENEF, TIPO, IDDEDUCBENEF_EMP, IDEMPLEADO, PROPORCIONALALSUELDO, MONTOOPORCENTAJE, FECHADEOPERACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDDEDUCBENEF, nombre_deduccion, tipo_deduccion, NEW.IDDEDUCBENEF_EMP, NEW.IDEMPLEADO, NEW.PROPORCIONALALSUELDO, NEW.MONTOOPORCENTAJE, NOW(), 'Inserción', user_id);
END$$
DELIMITER ;

-- Trigger para registrar la actualización en la tabla de bitácora
DELIMITER $$
CREATE TRIGGER `after_update_deduccionbeneficioempleado` AFTER UPDATE ON `deduccionbeneficio_empleado`
 FOR EACH ROW BEGIN
    DECLARE user_id INT;
    DECLARE nombre_deduccion VARCHAR(50);
    DECLARE tipo_deduccion CHAR(1);
    SET user_id = @current_user_id;

    SELECT NOMBREDEDUCBENEF, TIPO INTO nombre_deduccion, tipo_deduccion
    FROM DEDUCCIONBENEFICIO
    WHERE IDDEDUCBENEF = NEW.IDDEDUCBENEF;

    INSERT INTO AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO (IDDEDUCBENEF, NOMBREDEDUCBENEF, TIPO, IDDEDUCBENEF_EMP, IDEMPLEADO, PROPORCIONALALSUELDO, MONTOOPORCENTAJE, FECHADEOPERACION, TIPODEOPERACION, USUARIOREGISTRA)
    VALUES (NEW.IDDEDUCBENEF, nombre_deduccion, tipo_deduccion, NEW.IDDEDUCBENEF_EMP, NEW.IDEMPLEADO, NEW.PROPORCIONALALSUELDO, NEW.MONTOOPORCENTAJE, NOW(), 'Actualización', user_id);
END$$
DELIMITER ;