use bad_proyecto;
create table AUDITORIA_EMPLEADO
(
	IDAUDITORIA_EMPLEADO  int not null auto_increment,
   IDEMPLEADO           INT,
   IDPUESTO             int,
   IDMUNICIPIO          int,
   IDESTADOCIVIL        int,
   EMP_IDEMPLEADO       int,
   IDTIPODOC            int,
   NOMBRE1              varchar(20) not null,
   NOMBRE2              varchar(20),
   APELLIDO1            varchar(20) not null,
   APELLIDO2            varchar(20),
   APELLIDOCASADA       varchar(25),
   SEXO                 char(1) not null,
   FECHANACIMIENTO      date not null,
   FECHAINGRESO         datetime not null,
   NUMERODOC            varchar(20) not null,
   NIT                  varchar(25),
   ISSS                 varchar(25) not null,
   NUP                  varchar(25),
   SALARIO              decimal not null,
   CORREOINSTITUCIONAL  varchar(30) not null,
   CORREOPERSONAL       varchar(30) not null,
   ESTADO               bool not null default true,
   FECHAMODIFICACION 	DATETIME NOT NULL,
   TIPODEOPERACION VARCHAR(25) NOT NULL,
	 USUARIOREGISTRA INT,
   primary key (IDAUDITORIA_EMPLEADO)
);
ALTER TABLE AUDITORIA_EMPLEADO ADD CONSTRAINT FK_EMPLEADO FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADO (IDEMPLEADO);
ALTER TABLE AUDITORIA_EMPLEADO ADD CONSTRAINT FK_USUARIOMODIFICAEMPLEADO FOREIGN KEY (USUARIOREGISTRA) REFERENCES usuario(IDUSUARIO);
-- Añadir llave foránea a idpuesto
ALTER TABLE auditoria_empleado
ADD CONSTRAINT fk_idpuestoaudiemp
FOREIGN KEY (idpuesto) REFERENCES puesto(idpuesto);

-- Añadir llave foránea a idmunicipio
ALTER TABLE auditoria_empleado
ADD CONSTRAINT fk_idmunicipioaudiemp
FOREIGN KEY (idmunicipio) REFERENCES municipio(idmunicipio);

-- Añadir llave foránea a idestadocivil
ALTER TABLE auditoria_empleado
ADD CONSTRAINT fk_idestadocivilaudiemp
FOREIGN KEY (idestadocivil) REFERENCES estadocivil(idestadocivil);

-- Añadir llave foránea a emp_idempleado
ALTER TABLE auditoria_empleado
ADD CONSTRAINT fk_emp_idempleadoaudiemp
FOREIGN KEY (emp_idempleado) REFERENCES EMPLEADO (IDEMPLEADO);

-- Añadir llave foránea a idtipodoc
ALTER TABLE auditoria_empleado
ADD CONSTRAINT fk_idtipodocaudiemp
FOREIGN KEY (idtipodoc) REFERENCES tipodocumento(idtipodoc);


CREATE TABLE AUDITORIA_DEDUCCIONBENEFICIOGLOBAL(
	 IDAUDITORIA_IDDEDUCBENEF INT NOT NULL AUTO_INCREMENT,
	 IDDEDUCBENEF INT NOT NULL,
	 NOMBREDEDUCBENEF VARCHAR(50) NOT NULL,
	TIPO ENUM('D','B') NOT NULL,
	PROPORCIONALALSUELDO TINYINT(1) NOT NULL,
	MONTOOPORCENTAJE DECIMAL(10,0) NOT NULL,
	ESTADO TINYINT(1) NOT NULL DEFAULT '1',
	 FECHADEOPERACION DATE NOT NULL,
	 TIPODEOPERACION VARCHAR(25) NOT NULL,
	 USUARIOREGISTRA INT,
	 PRIMARY KEY(IDAUDITORIA_IDDEDUCBENEF)
	 
);
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOGLOBAL ADD CONSTRAINT FK_DEDUCCIONBENEFICIOGLOBAL FOREIGN KEY (IDDEDUCBENEF)
REFERENCES deduccionbeneficio(IDDEDUCBENEF) on delete restrict on update RESTRICT;
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOGLOBAL ADD CONSTRAINT FK_USUARIOREGISTRA FOREIGN KEY (USUARIOREGISTRA)
REFERENCES usuario(IDUSUARIO) on delete restrict on update RESTRICT;

CREATE TABLE AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO(
	 IDAUDITORIA_DEDUCBENEFEMP INT NOT NULL AUTO_INCREMENT,
	 IDDEDUCBENEF INT NOT NULL,
	 NOMBREDEDUCBENEF VARCHAR(50) NOT NULL,
	TIPO ENUM('D','B') NOT NULL,
	`IDDEDUCBENEF_EMP` INT(10) NOT NULL,
	`IDEMPLEADO` INT(10) NULL DEFAULT NULL,
	PROPORCIONALALSUELDO TINYINT(1) NOT NULL,
	MONTOOPORCENTAJE DECIMAL(10,0) NOT NULL,
	 FECHADEOPERACION DATE NOT NULL,
	 TIPODEOPERACION VARCHAR(25) NOT NULL,
	 USUARIOREGISTRA INT,
	 PRIMARY KEY(IDAUDITORIA_DEDUCBENEFEMP)
	 
);
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO ADD CONSTRAINT FK_DEDUCCIONBENEFICIOEMPAUDI FOREIGN KEY (IDDEDUCBENEF)
REFERENCES deduccionbeneficio(IDDEDUCBENEF) on delete restrict on update RESTRICT;
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO ADD CONSTRAINT FK_AUDI_DEDUFBENEFEMP_USUARIO FOREIGN KEY (USUARIOREGISTRA)
REFERENCES usuario(IDUSUARIO) on delete restrict on update RESTRICT;
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO ADD CONSTRAINT FK_DEDUCCIONBENEFICIOEMPLEADO FOREIGN KEY (IDDEDUCBENEF_EMP)
REFERENCES deduccionbeneficio_empleado(IDDEDUCBENEF_EMP) on delete restrict on update RESTRICT;
ALTER TABLE AUDITORIA_DEDUCCIONBENEFICIOEMPLEADO ADD CONSTRAINT FK_DEDUCCIONBENEFICIOEMPLEADOAUDIEMP FOREIGN KEY (IDEMPLEADO)
REFERENCES empleado(IDEMPLEADO) on delete restrict on update RESTRICT;