spring:
  config:
    import: "optional:file:.env[.properties]"

  application:
    name: planillas

  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
          hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  security:
    user:
      password: ${SPRING_SECURITY_PASSWORD}
      access_token_secret: ${ACCESS_TOKEN_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD_APP}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
